[book]
authors = ["Pietro"]
language = "pt-br"
src = "src"
title = "Los Broxas"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/elnpietro/Los-Broxas"
cname = "elnpietro.github.io/Los-Broxas/"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.embed]
